version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend